### ISSUE TITLE
ENOENT exception

### ISSUE THREAD

**Issue by itamir-outbrain** [notwaldorf/tiny-care-terminal#11]
Getting this error when trying to run:

Error: spawn bash /usr/local/lib/node_modules/tiny-care-terminal/standup-helper.sh ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn bash /usr/local/lib/node_modules/tiny-care-terminal/standup-helper.sh ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by FedericoMaggi** [comment]
At line 100 in `care.js` you get `[config.repos]` is used. Its default value is defined in config.js as:

```
config.repos = process.env.TTC_REPOS || '~/Code';
```

I think the *ENOENT* is related to that ~/Code directory missing (obiviously). As far as I understood you should set the environment variable `TTC_REPOS` to the directory where you are keeping your repositories.

**Comment by itamir-outbrain** [comment]
Changed the /Code reference, didn't help.

**Comment by notwaldorf** [comment]
Duplicate of #14 
There's a bunch of problems with `git-standup`; I'm just going to aggregate them under one issue

**Comment by notwaldorf** [comment]
Cross posted from #14:
OK! I published `1.0.4`  that _maybe_ works better? Anyone with a broken `tiny-care-terminal` want to install that and tell me if it's better, pretty please? 🙏

**Comment by taylor-kim** [comment]
@notwaldorf
i have had same error.
i hope fix it asap! :)

**Comment by matiasg** [comment]
I just installed version 1.1.1 and I still get this error.
I'm sorry I'm not a javascript/npm guy; I can't help here.
I've read #14 but couldn't get any insight from it.
